package com.farhetna.model;

public enum NotificationType {
    NEW_BOOKING_REQUEST,
    BOOKING_MODIFIED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_EXPIRED,
    CODE_EXPIRING_SOON,
    EVENT_REMINDER,
    RATING_REQUEST,
    NEW_RATING,
    OWNER_RESPONSE,
    SYSTEM_ANNOUNCEMENT,
    ACCOUNT_VERIFIED
}
